# Generated by Django 5.1.1 on 2024-10-05 12:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_alter_loginuser_phonenumber'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyDetails',
            fields=[
                ('companyName', models.CharField(max_length=250)),
                ('companyAddress', models.CharField(max_length=500)),
                ('companyPayment', models.CharField(max_length=50)),
                ('companyGST', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('quotationFor', models.CharField(max_length=200)),
                ('warrentyOf', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='QuotationTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('itemName', models.CharField(max_length=50)),
                ('itemDescription', models.CharField(max_length=500)),
                ('units', models.IntegerField()),
                ('price', models.IntegerField()),
                ('margin', models.IntegerField()),
                ('companyGST', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.companydetails')),
            ],
        ),
    ]
