# Generated by Django 5.1.1 on 2024-10-06 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_companydetails_quotationtable'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='companydetails',
            name='warrentyOf',
        ),
        migrations.AddField(
            model_name='companydetails',
            name='quotationType',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='quotationtable',
            name='warrentyYear',
            field=models.IntegerField(null=True),
        ),
    ]
