# Generated by Django 5.1.1 on 2024-10-08 06:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_remove_companydetails_warrentyof_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BOQQuotationTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('itemName', models.CharField(max_length=50)),
                ('itemDescription', models.CharField(max_length=500)),
                ('hsn_sac', models.CharField(max_length=20, null=True)),
                ('productSlNo', models.CharField(max_length=20, null=True)),
                ('partNo', models.CharField(max_length=20, null=True)),
                ('orderId', models.CharField(max_length=20, null=True)),
                ('partId', models.CharField(max_length=20, null=True)),
                ('warrentyYear', models.IntegerField(null=True)),
                ('startDate', models.DateField(null=True)),
                ('endDate', models.DateField(null=True)),
                ('instane', models.CharField(max_length=20, null=True)),
                ('contractId', models.CharField(max_length=20, null=True)),
                ('units', models.IntegerField()),
                ('price', models.IntegerField()),
                ('margin', models.IntegerField()),
                ('companyGST', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.companydetails')),
            ],
        ),
    ]
