# Generated by Django 5.1.1 on 2024-10-08 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_boqquotationtable'),
    ]

    operations = [
        migrations.AlterField(
            model_name='boqquotationtable',
            name='warrentyYear',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
