# Generated by Django 5.1.1 on 2024-10-09 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_boqquotationtable_totalunitprice'),
    ]

    operations = [
        migrations.AlterField(
            model_name='boqquotationtable',
            name='hsn_sac',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
