# Generated by Django 5.1.1 on 2024-10-10 05:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_alter_boqquotationtable_hsn_sac'),
    ]

    operations = [
        migrations.AddField(
            model_name='boqquotationtable',
            name='totalAmount',
            field=models.IntegerField(null=True),
        ),
    ]
