# Generated by Django 5.1.1 on 2024-10-18 05:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0011_boqquotationtable_quotationtype'),
    ]

    operations = [
        migrations.AddField(
            model_name='boqquotationtable',
            name='quotationNo',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
