# Generated by Django 5.1.1 on 2024-10-19 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0012_boqquotationtable_quotationno'),
    ]

    operations = [
        migrations.AddField(
            model_name='boqquotationtable',
            name='newMargin',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='boqquotationtable',
            name='newMarginPrice',
            field=models.IntegerField(null=True),
        ),
    ]
