# Generated by Django 5.1.1 on 2024-10-20 04:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0013_boqquotationtable_newmargin_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='companydetails',
            name='gstApply',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='companydetails',
            name='paymentTerms',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='companydetails',
            name='priceValidTill',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
