# Generated by Django 5.1.1 on 2024-10-21 05:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0014_companydetails_gstapply_companydetails_paymentterms_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='boqquotationtable',
            name='newMarginAppliedPrice',
            field=models.IntegerField(null=True),
        ),
    ]
