# Generated by Django 5.1.1 on 2024-10-23 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0015_boqquotationtable_newmarginappliedprice'),
    ]

    operations = [
        migrations.CreateModel(
            name='clientDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clientName', models.CharField(max_length=255)),
                ('Address', models.CharField(max_length=255, null=True)),
                ('GSTDetails', models.CharField(max_length=255, null=True)),
                ('concernPersonName', models.CharField(max_length=255, null=True)),
                ('Designation', models.CharField(max_length=255, null=True)),
                ('emailID', models.CharField(max_length=255, null=True)),
                ('phoneNo', models.CharField(max_length=255, null=True)),
            ],
            options={
                'db_table': 'clientDetails',
                'managed': False,
            },
        ),
    ]
