# Generated by Django 5.1.1 on 2024-11-05 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0016_clientdetails'),
    ]

    operations = [
        migrations.AlterField(
            model_name='boqquotationtable',
            name='orderId',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='boqquotationtable',
            name='partId',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='boqquotationtable',
            name='partNo',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
