# Generated by Django 5.1.1 on 2024-11-06 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0017_alter_boqquotationtable_orderid_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='boqquotationtable',
            name='price',
            field=models.CharField(max_length=50),
        ),
    ]
