# Generated by Django 5.1.1 on 2024-11-09 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0018_alter_boqquotationtable_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='boqquotationtable',
            name='lots',
            field=models.IntegerField(null=True),
        ),
    ]
