# Generated by Django 5.1.1 on 2024-11-12 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0019_boqquotationtable_lots'),
    ]

    operations = [
        migrations.AlterField(
            model_name='boqquotationtable',
            name='lots',
            field=models.IntegerField(default=1, null=True),
        ),
    ]
