# Generated by Django 5.1.1 on 2024-11-19 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0020_alter_boqquotationtable_lots'),
    ]

    operations = [
        migrations.AlterField(
            model_name='boqquotationtable',
            name='newMarginAppliedPrice',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='boqquotationtable',
            name='newMarginPrice',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='boqquotationtable',
            name='totalAmount',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='boqquotationtable',
            name='totalUnitPrice',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=12, null=True),
        ),
    ]
