# Generated by Django 5.1.1 on 2024-11-27 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0021_alter_boqquotationtable_newmarginappliedprice_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='boqquotationtable',
            name='newMargin',
            field=models.FloatField(null=True),
        ),
    ]
