# Generated by Django 5.1.4 on 2025-01-14 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0022_alter_boqquotationtable_newmargin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='boqquotationtable',
            name='itemName',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='quotationtable',
            name='itemName',
            field=models.CharField(max_length=500),
        ),
    ]
