# Generated by Django 5.1.4 on 2025-01-14 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0023_alter_boqquotationtable_itemname_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='boqquotationtable',
            name='itemName',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='quotationtable',
            name='itemName',
            field=models.TextField(),
        ),
    ]
