# Generated by Django 5.1.4 on 2025-01-17 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0024_alter_boqquotationtable_itemname_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='companydetails',
            name='deliverytime',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='companydetails',
            name='importantNote',
            field=models.CharField(max_length=500, null=True),
        ),
    ]
