# Generated by Django 5.1.4 on 2025-01-17 06:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0025_companydetails_deliverytime_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='companydetails',
            old_name='deliverytime',
            new_name='deliveryTime',
        ),
    ]
