# Generated by Django 5.1.4 on 2025-01-17 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0026_rename_deliverytime_companydetails_deliverytime'),
    ]

    operations = [
        migrations.AlterField(
            model_name='boqquotationtable',
            name='lots',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
