# Generated by Django 5.1.4 on 2025-01-27 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0027_alter_boqquotationtable_lots'),
    ]

    operations = [
        migrations.AlterField(
            model_name='boqquotationtable',
            name='productSlNo',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
